name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.6.0
        with:
          url: http://vault-poc-vault-lb-1766235720.us-east-1.elb.amazonaws.com
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
             kv-v2_1/11 2222 | app_secret

      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.app_secret }}" -t    vault-action-exampleapp
